---
title: "covid19"
author: "Dominic Skinnion"
date: "6/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r data, echo = FALSE}
countries_daily <- read_xlsx("raw-data/COVID-19-geographic-disbtribution-worldwide-2020-06-25.xlsx")
```

```{r data adding, echo = FALSE}
countries_per_cap <- countries_daily %>% 
  mutate(cases_per_cap = cases / popData2019)
```

```{r plot USA, echo = FALSE}
countries_daily %>%
  filter(countryterritoryCode == "USA") %>%
  ggplot(aes(x = dateRep, y = cases)) +
    geom_line()

countries_per_cap %>%
  filter(countryterritoryCode == "USA") %>%
  ggplot(aes(x = dateRep, y = cases_per_cap)) +
    geom_line()
```
```{r plot three countries, echo = FALSE}
countries_daily %>%
  filter(countryterritoryCode %in% c("USA", "ITA", "CHN")) %>%
  ggplot(aes(x = dateRep, y = cases, group = countryterritoryCode, color = countryterritoryCode)) +
    geom_line()

countries_per_cap %>%
  filter(countryterritoryCode %in% c("USA", "ITA", "CHN")) %>%
  ggplot(aes(x = dateRep, y = cases_per_cap, group = countryterritoryCode, color = countryterritoryCode)) +
    geom_line()
```

```{r splitting into individual country tibbles, echo = FALSE}

n <- unique(countries_daily$countryterritoryCode)
n <- as.character(n)

total_case_fxn <- function(country) {
  object <- countries_daily %>%
    filter(countryterritoryCode == country) 
  
  assign(paste(country), data.frame(object), envir = .GlobalEnv)
}

map(n, total_case_fxn)
```







